version: "3"

tasks:
  default:
    cmds:
      - task: watch
    deps:
      - install
      - setup

  version:
    cmds:
      - pnpm version patch
    desc: "Обновление версии проекта (patch)"

  build:
    cmd: pnpm run package
    deps:
      - install
      - setup
      - type-check

  build-fast:
    desc: "Быстрая сборка без переустановки зависимостей"
    cmd: node esbuild.js --production
    deps:
      - setup

  watch:
    cmd: pnpm run watch
    deps:
      - install
      - setup
      - type-check

  setup:
    desc: "Настройка проекта: копирование .env файла"

    cmds:
      - >
        {{if eq OS "windows"}} powershell {{end}} cp .env.example .env
    status:
      - test -f .env

  install:
    cmd: pnpm install && pnpm add graphql-ws
    run: once
    status:
      - test -d node_modules
      - test -d node_modules/graphql-ws

  type-check:
    cmd: pnpm tsc --noEmit
    deps:
      - install
