version: "3"

tasks:
  default:
    cmds:
      - task: watch
    deps:
      - install

  version:
    cmds:
      - pnpm version patch
    desc: "Обновление версии проекта (patch)"

  build:
    cmd: pnpm run package
    deps:
      - install
      - type-check

  build-fast:
    desc: "Быстрая сборка без переустановки зависимостей"
    cmd: node esbuild.js --production

  watch:
    cmd: pnpm run watch
    deps:
      - install
      - type-check

  install:
    cmd: pnpm install && pnpm add graphql-ws
    run: once
    status:
      - test -d node_modules
      - test -d node_modules/graphql-ws

  type-check:
    cmd: pnpm tsc --noEmit
    deps:
      - install
